// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_dUhx8FJMKM_L-tFtVTf66fJ_mzoKObU',
    appId: '1:595568555972:ios:0a52af70d32dfbbbd05691',
    messagingSenderId: '595568555972',
    projectId: 'cupid-13c00',
    storageBucket: 'cupid-13c00.firebasestorage.app',
    iosBundleId: 'com.makerdaryl.cupid',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_qAV5ixC7O_1i4uHoqmKSRisNGPNZAIY',
    appId: '1:595568555972:android:9eb3077cb606eb1ed05691',
    messagingSenderId: '595568555972',
    projectId: 'cupid-13c00',
    storageBucket: 'cupid-13c00.firebasestorage.app',
  );

}